export const sidebardata = [
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 1,
    type: "",
    uuid: "d0caec46-cdfa-46ad-bf95-0e404a9caced",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "9ecc30a7-0125-422d-9931-c0bac887e9b2",
        route: "/f28bde11-f255-4bf2-9d9d-fb8f7555c0d4",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "Widgets",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 2,
        type: "Pages",
        uuid: "1337b01c-d487-4db6-93d1-9b619d125744",
        route: "/c8ac0bcc-43e6-4fa2-87fb-392c2c741e14",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "Address",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 3,
        type: "Pages",
        uuid: "2699bdb4-81d2-4f7d-a448-4da1dcdf8be9",
        route: "/9d633401-df42-44f0-b32c-1c2406ab43af",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "Lead",
        default_homepage_type: "",
      },
    ],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "JSON FORM ",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 2,
    type: "",
    uuid: "45c36bb3-e529-4b45-b20e-cb27bfd0f6a9",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "a2ba1ae1-d9a0-4312-adb2-30acdaab04bc",
        route: "/c409dda8-0a7a-4983-ba09-4ad48433e47b",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "Case2",
        default_homepage_type: "",
      },
    ],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "Amazone",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 3,
    type: "Pages",
    uuid: "01466db2-d797-4816-a729-0770508153ba",
    route: "/ee2d2b32-4ebb-4078-b08f-a40da92fc6e3",
    app_id: "76537078-ae81-434e-9ad9-679dc74b648c",
    children: [],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "jobtitle",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 4,
    type: "Pages",
    uuid: "2325838e-7763-428b-8dcc-3428b92dec50",
    route: "/9db8e32d-1d14-451d-8689-4fff8b8aa2aa",
    app_id: "76537078-ae81-434e-9ad9-679dc74b648c",
    children: [],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "users",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 5,
    type: "Pages",
    uuid: "3fe43b1b-53cd-4129-9e75-992f7bf24dee",
    route: "/bbcfee7f-6b44-4356-bacd-d1e7a39c8ec9",
    app_id: "76537078-ae81-434e-9ad9-679dc74b648c",
    children: [],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Automation Flow",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 6,
    type: "",
    uuid: "dc903dca-912b-43d8-9d17-4cd1ee324d8e",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "099b1b01-4998-4a5e-b9aa-7d08c591fddb",
        route: "/23d55c43-1e65-4ec0-b420-cb391d0626e4",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "case of Multi-test points",
        default_homepage_type: "",
      },
    ],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "Multi test Points",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 7,
    type: "",
    uuid: "0658b198-f210-45c1-b041-f4616222c1f4",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "b648cb85-db85-40d5-b42a-a46d068dc906",
        route: "/03071d02-590f-48f7-9045-558741c51ff6",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "crud",
        default_homepage_type: "",
      },
    ],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "sharath",
  },
  {
    icon: {
      svg: "bell-on",
      name: "insert_emoticon",
      type: "material-icons",
      color: "#5f6368",
      style: "solid",
      imgurl: "https://static.amoga.io/fa/solid/bell-on.svg",
      version: 1,
    },
    rank: 8,
    type: "Pages",
    uuid: "aeb16e66-cc24-4446-9c23-9aeb4e3d9334",
    route: "/6300a65f-9e77-4ad8-9608-bcc32955a146",
    app_id: "9962cd1b-996d-470b-85b7-3583606912b5",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Notify",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "masks-theater",
      name: "insert_emoticon",
      type: "material-icons",
      color: "#5f6368",
      style: "light",
      imgurl: "https://static.amoga.io/fa/light/masks-theater.svg",
      version: 1,
    },
    rank: 9,
    type: "",
    uuid: "51eec964-71c3-48be-8962-e4722544ea4f",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "ab6642d1-d4c6-4388-b999-868c737764ea",
        route: "/9d6d5ffc-04a2-42e5-bf7c-349c86ca850e",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "Case",
        default_homepage_type: "",
      },
    ],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "Amoga Page",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 10,
    type: "",
    uuid: "5945811f-7f54-4324-8ef5-88da5c5ab52e",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "b77da262-69a7-4037-b50f-6e3effb79e20",
        route: "/97d3420d-de74-4602-a679-689456da8323",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "bus obj",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "meteor",
          name: "insert_emoticon",
          type: "material-icons",
          color: "#5f6368",
          style: "solid",
          imgurl: "https://static.amoga.io/fa/solid/meteor.svg",
          version: 1,
        },
        rank: 2,
        type: "Pages",
        uuid: "53819bbf-2d3d-4165-8c47-0bb90752aab6",
        route: "/718e3799-6071-4390-a447-2e9242ff9a02",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "case ",
        default_homepage_type: "",
      },
    ],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "App Raghvendra",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 11,
    type: "",
    uuid: "b8c88825-b13c-4c68-98a5-e21c4e6e40c4",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "d6cdda03-9b9e-4f5b-84f5-d7a5d3fd0a6d",
        route: "/0e0599b7-2de6-4b1c-b2ed-cf9225feee4b",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "lead",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 2,
        type: "Pages",
        uuid: "1b7b425e-b880-4471-940f-9c18e1c7b349",
        route: "/520fd083-00c3-4c5a-a2cb-4d69a85f5549",
        app_id: "",
        children: [],
        is_active: true,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "vaibhav BO1",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "memo",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 3,
        type: "Pages",
        uuid: "2b46709b-5912-4232-aab0-cddf5ba2a90b",
        route: "/0e0599b7-2de6-4b1c-b2ed-cf9225feee4b",
        app_id: "ebfc9949-10aa-470b-9bd5-7834eb06050e",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "vaibhav app lead",
        default_homepage_type: "",
      },
    ],
    is_active: true,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "vaibhav app",
  },
  {
    icon: {
      svg: "memo",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 12,
    type: "Pages",
    uuid: "ffcb2f70-f8b0-4bf6-ad9f-4d2ec9a16d96",
    route: "/d3f42e78-4593-4c6a-b973-ab2a08875566",
    app_id: "ebfc9949-10aa-470b-9bd5-7834eb06050e",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Palak's lead",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "integral",
      name: "insert_emoticon",
      type: "material-icons",
      color: "#5f6368",
      style: "solid",
      imgurl: "https://static.amoga.io/fa/solid/integral.svg",
      version: 1,
    },
    rank: 13,
    type: "",
    uuid: "3c2da77e-9c9e-40f3-837c-6d75ca09a375",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "location-dot",
          name: "insert_emoticon",
          type: "material-icons",
          color: "#5f6368",
          style: "solid",
          imgurl: "https://static.amoga.io/fa/solid/location-dot.svg",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "2b5695ea-730b-4d0e-9ed4-d90d2e0c03d3",
        route: "/4a15c9e6-b36b-451e-b555-1e359080f05e",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "third",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "face-smile",
          name: "11mp",
          type: "material-icons-outlined",
          color: "#5f6368",
          style: "solid",
          version: 1,
        },
        rank: 2,
        type: "Pages",
        uuid: "9515a1e6-9f54-422b-9f37-506e70f9e454",
        route: "/9afeff79-5dd1-453a-9efe-2fc8fbadc9f9",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "second",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "house",
          name: "insert_emoticon",
          type: "material-icons",
          color: "#5f6368",
          style: "solid",
          imgurl: "https://static.amoga.io/fa/solid/house.svg",
          version: 1,
        },
        rank: 3,
        type: "Pages",
        uuid: "b9ded17c-d791-4b3d-9267-41119cb92c05",
        route: "/7111b0df-aa94-4059-ac34-5f7e288ee0ff",
        app_id: "bc6c2e93-5eaf-4ca9-af64-bd72e7d315f8",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "first",
        default_homepage_type: "",
      },
    ],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "measures",
  },
  {
    icon: {
      svg: "face-smile",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 14,
    type: "Pages",
    uuid: "0b6707d3-1a74-41de-8216-d5373dfa8ef2",
    route: "/871cba6f-ddcc-4d34-b043-9870fde228e4",
    app_id: "ebfc9949-10aa-470b-9bd5-7834eb06050e",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Primary Task",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "window-restore",
      name: "insert_emoticon",
      type: "material-icons",
      color: "#5f6368",
      style: "solid",
      imgurl: "https://static.amoga.io/fa/solid/window-restore.svg",
      version: 1,
    },
    rank: 15,
    type: "Pages",
    uuid: "51f5a3cb-71dc-46f1-b0a1-0e39367a4e7d",
    route: "/30612a53-3bd5-433c-bca3-fb6fe93f4b48",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "State",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "wrench",
      name: "insert_emoticon",
      type: "material-icons",
      color: "#9fa5fe",
      style: "light",
      imgurl: "https://fa.amoga.io/light/wrench.svg",
      version: 1,
    },
    rank: 16,
    type: "Pages",
    uuid: "98f47a24-1aa9-4c88-90fb-8c674a7ae381",
    route: "/62d4535f-3d11-4a95-a225-650f33f8f445",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "test 22",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "yin-yang",
      name: "insert_emoticon",
      type: "material-icons",
      color: "#5f6368",
      style: "solid",
      imgurl: "https://static.amoga.io/fa/solid/yin-yang.svg",
      version: 1,
    },
    rank: 17,
    type: "Pages",
    uuid: "12e47657-ee55-4c9f-a651-dc7108b0853d",
    route: "/f1910d2b-0183-4264-a42b-9d4222f3146c",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Test",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "face-smile",
      name: "11mp",
      type: "material-icons-outlined",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    rank: 18,
    type: "",
    uuid: "f2924d80-a0d0-4f30-ac33-207770f80435",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "bolt",
          name: "insert_emoticon",
          type: "material-icons",
          color: "#5f6368",
          style: "solid",
          imgurl: "https://static.amoga.io/fa/solid/bolt.svg",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "76b418c3-20f1-4c5b-9c21-4d1fd2c61bfe",
        route: "/0e0599b7-2de6-4b1c-b2ed-cf9225feee4b",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "Test2",
        default_homepage_type: "",
      },
    ],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "Test User",
  },
  {
    icon: {
      svg: "yen-sign",
      name: "insert_emoticon",
      type: "material-icons",
      color: "#ff8800",
      style: "solid",
      imgurl: "https://static.amoga.io/fa/solid/yen-sign.svg",
      version: 1,
    },
    rank: 19,
    type: "",
    uuid: "9ab72318-6d2f-4abd-aeb5-2c70d4b414a6",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "z",
          name: "insert_emoticon",
          type: "material-icons",
          color: "#e2e462",
          style: "light",
          imgurl: "https://fa.amoga.io/light/z.svg",
          version: 1,
        },
        rank: 1,
        type: "Pages",
        uuid: "19f9c8d8-0881-413e-a4e4-edacfde51fd9",
        route: "/1f683aa8-52e8-4f44-89b9-2dfacf40bb70",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "test 1",
        default_homepage_type: "",
      },
      {
        icon: {
          svg: "wine-glass-empty",
          name: "insert_emoticon",
          type: "material-icons",
          color: "#ffb3b3",
          style: "light",
          imgurl: "https://fa.amoga.io/light/wine-glass-empty.svg",
          version: 1,
        },
        rank: 2,
        type: "Pages",
        uuid: "f9af26c3-b5d9-4c28-a020-f326e85447a5",
        route: "/1f683aa8-52e8-4f44-89b9-2dfacf40bb70",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: true,
        meta_data: {},
        view_type: "item",
        is_default: false,
        display_name: "test icon item",
        default_homepage_type: "",
      },
    ],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "group",
    is_default: false,
    display_name: "Test Icons",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 20,
    type: "Pages",
    uuid: "3034ee99-e39b-4235-b024-4fa64f5f6719",
    route: "/fa2b83a6-19f9-4702-9773-cf6350663508",
    app_id: "ebfc9949-10aa-470b-9bd5-7834eb06050e",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Vaibhav's app",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 21,
    type: "Pages",
    uuid: "7d73ecdd-2e9e-406b-91ee-706f1fb16547",
    route: "/808def23-ab62-4f5d-b257-d7453bf63776",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "MyHub",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 22,
    type: "View",
    uuid: "eaa7b514-c258-4398-b571-4cec589f04a1",
    route:
      "/work/2660932d-cf8f-45fe-a3a2-4162ef08d48f?type=tasks&selectedWorkItem=all&saved_views=tasks",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "test",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 23,
    type: "Pages",
    uuid: "838b592a-b0d3-4fb1-b1a6-b78761142324",
    route: "/390115c2-d0c0-4746-a64d-8ec61a5c4045",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "SD Public School > Student",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 24,
    type: "Pages",
    uuid: "cb12d77f-5716-40db-a2b2-971319518633",
    route: "/c1e54f92-9869-462b-a3ac-0fbe955d5f55",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Margin Money",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 25,
    type: "Pages",
    uuid: "2c34f635-99b3-4a3c-9233-85cd9a14e6f1",
    route: "/18c19eca-be2b-402e-b903-9742f321ed0d",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "test",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 26,
    type: "Pages",
    uuid: "df6a9d20-b2e4-489d-988a-22b5e11db25e",
    route: "/a59f8031-6943-4a55-ad7d-31136ff3d8d5",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Loan",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 27,
    type: "Pages",
    uuid: "2f696b24-151e-4cc9-8dc9-449677f9dcc9",
    route: "/bcffc009-4375-4ba1-a017-1c91f05a2670",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "lead",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 28,
    type: "Pages",
    uuid: "a51564c3-039e-46e2-b802-788b3d4eea2b",
    route: "/fdd0d5a7-dd18-449a-a36d-6d57fe251e7b",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "Job Title",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "camera",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 29,
    type: "Pages",
    uuid: "b07a716a-40b6-43ad-a466-44a0b7f50551",
    route: "/5fc97903-a108-4f47-a818-c1036a1b5334",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: false,
    display_name: "User List",
    default_homepage_type: "",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 30,
    type: "module",
    uuid: "5155c9d2-0039-4082-836f-ec6901777163",
    route: "/820cac08-636b-4218-a8ab-bc5c54d268da",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: false,
    view_type: "item",
    is_default: true,
    workitem_id: "",
    display_name: "Hub",
  },
  {
    icon: {
      svg: "film",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 31,
    type: "module",
    uuid: "7bf2de2a-2a44-422c-92bf-d963b293e77c",
    route: "",
    app_id: "",
    children: [
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        type: "module",
        uuid: "e348dc55-bcce-44d4-9cfb-531f014df0db",
        route: "/2b8626a5-54b7-4817-9688-04f3fe1be43c",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        display_name: "Workitems Page",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 2,
        type: "module",
        uuid: "d109a0a1-b0f0-49a7-9fae-74051992fcce",
        route: "/718d9e87-46c2-448a-95ff-3da04ac5042c",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        display_name: "Tasks Page",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 3,
        type: "module",
        uuid: "d14c9088-8056-41e3-a694-c169fb54680f",
        route: "/4584b236-2c79-488e-95d8-923a8fb2e3d9",
        app_id: "",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        display_name: "Business Object Page",
      },
    ],
    is_active: false,
    is_custom: false,
    view_type: "group",
    is_default: true,
    display_name: "Shubham App Pages",
  },
  {
    icon: {
      svg: "hashtag",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 32,
    type: "module",
    uuid: "90ede068-a430-473f-9345-7f9923f71b3f",
    route: "/hub",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: true,
    meta_data: {},
    view_type: "item",
    is_default: true,
    display_name: "Hub",
    default_homepage_type: "module",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 33,
    type: "module",
    uuid: "0fcbe2b9-ef5a-46c8-b938-b10d1cff979e",
    route: "/goal",
    app_id: "",
    children: [
      {
        icon: {
          svg: "bullseye",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        uuid: "40f27715-46cb-4ad1-a01a-813352cf8132",
        route: "/goal?level=all_reports",
        app_id: "",
        children: [],
        is_active: false,
        view_type: "item",
        is_default: true,
        display_name: "Reports OKRs",
      },
      {
        icon: {
          svg: "bullseye",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 2,
        uuid: "3b8b2edc-1dcb-4ed8-afc3-f7e9acfd615d",
        route: "/goal?level=team",
        app_id: "",
        children: [],
        is_active: false,
        view_type: "item",
        is_default: true,
        display_name: "Team OKRs",
      },
      {
        icon: {
          svg: "bullseye",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 3,
        uuid: "eec02e68-77fd-46a1-af3c-fdf2c76a43cb",
        route: "/goal?level=all",
        app_id: "",
        children: [],
        is_active: false,
        view_type: "item",
        is_default: true,
        display_name: "All OKRs",
      },
    ],
    is_active: false,
    view_type: "group",
    is_default: true,
    display_name: "Goals",
  },
  {
    icon: {
      svg: "chart-line",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 34,
    type: "module",
    uuid: "0fcbe2b9-ef5a-26c8-b938-b10d1cff979e",
    route: "/scorecard",
    app_id: "",
    children: [
      {
        icon: {
          svg: "gauge-high",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        uuid: "b2b596d6-bbee-4447-a4d1-7b3994babc11",
        route: "/scorecard",
        app_id: "",
        children: [],
        is_active: false,
        view_type: "item",
        is_default: true,
        display_name: "User Scorecard",
      },
    ],
    is_active: false,
    view_type: "group",
    is_default: true,
    display_name: "Growth",
  },
  {
    icon: {
      svg: "chart-bar",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 35,
    type: "module",
    uuid: "0fdbe2b9-ef5a-46c8-b938-b10d1cff979e",
    route: "/analytics-dashboard",
    app_id: "",
    children: [
      {
        icon: {
          svg: "file-check",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        uuid: "a361a5ed-f96c-4f69-987f-ace63efeb7ce",
        route: "/analytics",
        app_id: "",
        children: [],
        is_active: true,
        view_type: "item",
        is_default: true,
        display_name: "Dashboard",
        dashboard: [],
      },
      {
        icon: {
          svg: "file-check",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 2,
        uuid: "acc921a2-eba8-4b8b-8e3f-1cd63bf52779",
        route: "/analytics-reports",
        app_id: "",
        children: [],
        is_active: true,
        view_type: "item",
        is_default: true,
        display_name: "Report",
      },
    ],
    is_active: true,
    view_type: "group",
    is_default: true,
    display_name: "Analytics",
  },
  {
    icon: {
      svg: "paw",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    page: true,
    rank: 36,
    type: "module",
    uuid: "53a46665-8e4a-4a76-baae-bbc737a14e00",
    route: "/ebfc9949-10aa-470b-9bd5-7834eb06050e",
    app_id: "ebfc9949-10aa-470b-9bd5-7834eb06050e",
    children: [
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        type: "module",
        uuid: "bd9683ae-9f0e-4d60-a278-776a81979807",
        route: "/page/d31cb77a-416a-4864-a172-dbdf7df36cad",
        app_id: "ebfc9949-10aa-470b-9bd5-7834eb06050e",
        children: [],
        is_active: true,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: "",
        display_name: "DB Dashboard Page",
      },
    ],
    is_active: false,
    is_custom: false,
    view_type: "group",
    is_default: true,
    display_name: "Vaibhav's app Pages",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 37,
    type: "module",
    uuid: "deb00e1b-6d74-4bc6-9aa4-d8880af72dbd",
    route: "/933bf1fe-a1c3-4a03-a0ac-e4e816811f83",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: false,
    view_type: "item",
    is_default: true,
    workitem_id: "",
    display_name: "Settings",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 38,
    type: "module",
    uuid: "689f2156-90d4-49a4-a770-9cababc9d2af",
    route: "/71df7a1f-be77-448b-8665-9d24b91079f4",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: false,
    view_type: "item",
    is_default: true,
    workitem_id: "",
    display_name: "Goal",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 39,
    type: "module",
    uuid: "14f38dc5-be33-4bd4-b461-97a4f8c7fef6",
    route: "/5b6014c4-7806-47b9-a7ac-9663f35e9c20",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: false,
    view_type: "item",
    is_default: true,
    workitem_id: "",
    display_name: "Automation",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 40,
    type: "module",
    uuid: "d65b6b8f-4c64-4048-8b31-e054ea41729f",
    route: "/hub",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: false,
    view_type: "item",
    is_default: true,
    workitem_id: "",
    display_name: "Hub",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 41,
    type: "module",
    uuid: "28285a66-c30d-497d-9847-0690914edbd8",
    route: "/settings",
    app_id: "",
    children: [],
    is_active: false,
    is_custom: false,
    view_type: "item",
    is_default: true,
    workitem_id: "",
    display_name: "Settings",
  },
  {
    icon: {
      svg: "bars",
      color: "#5f6368",
      style: "light",
      version: 1,
    },
    rank: 42,
    type: "module",
    uuid: "5e44beae-f8c1-4ab9-b514-1b1f089c2f65",
    route: "/automation",
    app_id: "",
    children: [],
    is_active: true,
    is_custom: false,
    view_type: "item",
    is_default: true,
    workitem_id: "",
    display_name: "Automation",
  },
  {
    icon: null,
    page: true,
    rank: 43,
    type: "module",
    uuid: "1280b8e8-7bfc-4e6a-b4af-17cfc497a581",
    route: "/9b306f94-e88f-47e0-9ed0-bd1d71e524df",
    app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
    children: [
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        type: "module",
        uuid: "3d15c372-3e49-4f39-8fcf-6e01c08949b7",
        route: "/4ffd3944-a7f9-443b-878f-6cef0e27db37",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: null,
        display_name: "Measures_1 dashboard",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 2,
        type: "module",
        uuid: "6d2d0a52-16cb-4b2f-90f7-24b55f55c5dc",
        route: "/97331d29-e160-4467-958e-6fb0c8841003",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: null,
        display_name: "Measures_2 dashboard",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 3,
        type: "module",
        uuid: "ff6d4b50-d72f-49ac-82c0-1ed2eb7ea3b3",
        route: "/bd9edd6c-4d00-489d-b4eb-1343c24b210e",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: null,
        display_name: "Measures_3 dashboard",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 4,
        type: "module",
        uuid: "544968de-7dd9-42f1-9e37-f084d20dd005",
        route: "/886955c4-caae-466c-9aba-62613f9388b7",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: 3041,
        display_name: "Case dashboard",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 5,
        type: "module",
        uuid: "d7bd1772-2fcc-4f15-adc1-a9a4625612de",
        route: "/629c63c7-1d01-454b-bc37-967c716fb0c1",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: 3041,
        display_name: "Case record",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 6,
        type: "module",
        uuid: "2b3f2a83-0064-4e48-84df-2a700787b84b",
        route: "/42d7e20a-d366-46e1-ab38-4242311a329e",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: 3040,
        display_name: "Task 2 dashboard",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 7,
        type: "module",
        uuid: "d4c6ccef-026a-4384-ab47-137bccdd97a4",
        route: "/c3adf19b-b050-452c-8948-074283269d00",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: 3041,
        display_name: "Case Create Form record",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 8,
        type: "module",
        uuid: "30ad1b93-cad7-44ef-b949-175cc136c802",
        route: "/ad615e78-c995-4fb0-bb9d-3adea62693bf",
        app_id: "9b306f94-e88f-47e0-9ed0-bd1d71e524df",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: 3040,
        display_name: "Task 2 record",
      },
    ],
    is_active: false,
    is_custom: false,
    view_type: "group",
    is_default: true,
    display_name: "Measures Pages",
  },
  {
    icon: {
      svg: "memo",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    page: true,
    rank: 44,
    type: "module",
    uuid: "361d7993-56f4-4f60-85e2-86540b93d2ae",
    route: "/75647a0f-a528-4ec0-b0ab-5477515df720",
    app_id: "75647a0f-a528-4ec0-b0ab-5477515df720",
    children: [],
    is_active: false,
    is_custom: false,
    view_type: "group",
    is_default: true,
    display_name: "Maxwell High School Pages",
  },
  {
    icon: {
      svg: "memo",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    page: true,
    rank: 46,
    type: "module",
    uuid: "ae06988e-03bb-4c20-afc6-2a049a05d333",
    route: "/fb5ca03e-f5aa-4777-ace2-7d4df8967b8d",
    app_id: "fb5ca03e-f5aa-4777-ace2-7d4df8967b8d",
    children: [
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        type: "module",
        uuid: "0df51c9a-a3fa-4552-b252-8a730a6cfc7f",
        route: "/f26d5fff-b004-4215-892a-b1ddc8fc5ce6",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        display_name: "Workitems Page",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 2,
        type: "module",
        uuid: "c9062164-7d88-4453-be34-f5a99e37c969",
        route: "/10365055-9468-49a1-bd6a-e33e2dbe87e8",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        display_name: "Tasks Page",
      },
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 3,
        type: "module",
        uuid: "20f8c9af-d8c9-44a9-a241-dd29b9a7d085",
        route: "/3769a160-5afb-42e9-a341-edcde48aeb81",
        children: [],
        is_active: false,
        is_custom: false,
        view_type: "item",
        is_default: true,
        display_name: "Business Object Page",
      },
    ],
    is_active: false,
    is_custom: false,
    view_type: "group",
    is_default: true,
    display_name: "Palak's App Pages",
  },
  {
    icon: {
      svg: "memo",
      color: "#5f6368",
      style: "solid",
      version: 1,
    },
    page: true,
    rank: 49,
    type: "module",
    uuid: "92fe60d9-93d7-40d0-8994-b69915515fae",
    route: "/9962cd1b-996d-470b-85b7-3583606912b5",
    app_id: "9962cd1b-996d-470b-85b7-3583606912b5",
    children: [
      {
        icon: {
          svg: "bars",
          color: "#5f6368",
          style: "light",
          version: 1,
        },
        rank: 1,
        type: "module",
        uuid: "9a5ab2e8-2fb1-45d7-b722-828346f9eeed",
        route: "/page/fc0b1a00-0927-4d35-9f81-d039707d5caf",
        app_id: "9962cd1b-996d-470b-85b7-3583606912b5",
        children: [],
        is_active: true,
        is_custom: false,
        view_type: "item",
        is_default: true,
        workitem_id: "3362",
        display_name: "asdfgh Dashboard Page",
      },
    ],
    is_active: false,
    is_custom: false,
    view_type: "group",
    is_default: true,
    display_name: "Amoga Pages V2 Pages",
  },
];